export default {
  login: 'tejbhatt',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/tejbhatt',
  html_url: 'https://github.com/tejbhatt',
  followers_url: 'https://api.github.com/users/tejbhatt/followers',
  following_url:
    'https://api.github.com/users/tejbhatt/following{/other_user}',
  gists_url: 'https://api.github.com/users/tejbhatt/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/tejbhatt/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/tejbhatt/subscriptions',
  organizations_url: 'https://api.github.com/users/tejbhatt/orgs',
  repos_url: 'https://api.github.com/users/tejbhatt/repos',
  events_url: 'https://api.github.com/users/tejbhatt/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/tejbhatt/received_events',
  type: 'User',
  site_admin: false,
  name: 'Tej Bhatt',
  company: 'trellisys',
  blog: '',
  location: 'Thane,India',
  email: null,
  hireable: null,
  bio: '',
  twitter_username: 'tejbhatt98',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2023-04-18T06:48:23Z',
  updated_at: '2023-04-18T05:01:32Z',
};
